"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { AuthGuard } from "@/components/layout/AuthGuard";
import { apiFetch, jsonBody } from "@/lib/api";
import { useAuthStore } from "@/stores/auth";
import type { CatalogItem, InteractionPayload } from "@/types/api";

function MovieDetailContent() { const params = useParams<{ id: string }>(); const token = useAuthStore((state) => state.token); const queryClient = useQueryClient(); const query = useQuery({ queryKey: ["movie", params.id], queryFn: () => apiFetch<CatalogItem>(`/api/v1/catalog/${params.id}`, {}, token!), enabled: Boolean(token && params.id) }); const interaction = useMutation({ mutationFn: (event_type: InteractionPayload["event_type"]) => apiFetch("/api/v1/interactions", { ...jsonBody({ catalog_item_id: Number(params.id), event_type, source_page: `/movies/${params.id}` }) }, token!), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["recommendations", "movie"] }) }); const favorite = useMutation({ mutationFn: () => apiFetch<{ is_favorite: boolean }>(`/api/v1/favorites/${params.id}`, { ...jsonBody({}) }, token!), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["favorites"] }) }); if (query.isLoading) return <main className="center-page"><p>Chargement du film…</p></main>; if (query.error || !query.data) return <main className="center-page"><div className="form-card"><h1>Film introuvable</h1><Link className="button" href="/movies">Retour aux films</Link></div></main>; const movie = query.data; return <main className="detail"><Link href="/movies" className="eyebrow">← Tous les films</Link><div className="detail-layout" style={{ marginTop: 25 }}><div>{movie.image_url ? <img className="detail-poster" src={movie.image_url} alt={`Affiche de ${movie.title}`} /> : <div className="detail-poster poster-placeholder">🎬</div>}</div><div><p className="eyebrow">Film</p><h1>{movie.title}</h1><p className="meta">{movie.release_date?.slice(0, 4) ?? "Date inconnue"} · {movie.runtime_minutes ? `${movie.runtime_minutes} min · ` : ""}{movie.genres?.join(" · ")}</p>{movie.average_rating ? <p className="rating">★ {movie.average_rating.toFixed(1)} / 10 ({movie.rating_count} votes)</p> : null}<p className="description">{movie.description || "Aucun synopsis disponible."}</p><div className="detail-actions"><button className="button" onClick={() => interaction.mutate("like")}>♥ J’aime</button><button className="button secondary" onClick={() => interaction.mutate("dislike")}>Je n’aime pas</button><button className="button secondary" onClick={() => favorite.mutate()}>☆ Favori</button>{movie.trailer_url && <a className="button secondary" href={movie.trailer_url} target="_blank" rel="noreferrer" onClick={() => interaction.mutate("trailer_play")}>▶ Bande-annonce</a>}</div>{interaction.isSuccess && <p className="reason">Votre signal a été enregistré. Les recommandations vont être actualisées.</p>}</div></div></main>; }
export default function MovieDetailPage() { return <AuthGuard><MovieDetailContent /></AuthGuard>; }
