"use client";

import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { AuthGuard } from "@/components/layout/AuthGuard";
import { apiFetch, ApiError } from "@/lib/api";
import { useAuthStore } from "@/stores/auth";
import type { AdminMetrics } from "@/types/api";
import { EbaySyncButton } from "@/components/admin/EbaySyncButton";

function AdminContent() { const token = useAuthStore((state) => state.token); const queryClient = useQueryClient(); const query = useQuery({ queryKey: ["admin", "metrics"], queryFn: () => apiFetch<AdminMetrics>("/api/v1/admin/metrics", {}, token!), enabled: Boolean(token) }); const sync = useMutation({ mutationFn: () => apiFetch<{ status: string; received: number; created: number; updated: number; failed: number }>("/api/v1/admin/sync/tmdb", { method: "POST" }, token!), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["admin", "metrics"] }) }); if (query.isLoading) return <main className="center-page"><p>Chargement des métriques…</p></main>; if (query.error) return <main className="center-page"><div className="form-card"><h1>Accès refusé</h1><p className="error">{query.error instanceof ApiError ? query.error.detail : "Cette page est réservée aux administrateurs."}</p></div></main>; const metrics = query.data!; return <main className="page"><div className="hero"><div><p className="eyebrow">Pilotage</p><h1>Administration.</h1><p>Surveillez le catalogue et les synchronisations.</p></div><button className="button" disabled={sync.isPending} onClick={() => sync.mutate()}>{sync.isPending ? "Synchronisation…" : "Synchroniser TMDB"}</button><EbaySyncButton /></div>{sync.data && <p className="reason">Synchronisation {sync.data.status} : {sync.data.created} créés, {sync.data.updated} mis à jour, {sync.data.failed} erreurs.</p>}{sync.error && <p className="error">{sync.error instanceof ApiError ? sync.error.detail : "La synchronisation a échoué."}</p>}<div className="stats"><div className="stat"><strong>{metrics.users}</strong><span>Utilisateurs</span></div><div className="stat"><strong>{metrics.movies}</strong><span>Films</span></div><div className="stat"><strong>{metrics.interactions}</strong><span>Interactions</span></div><div className="stat"><strong>{metrics.favorites}</strong><span>Favoris</span></div></div><section className="section"><h2>Dernières synchronisations</h2>{Object.entries(metrics.last_sync).map(([source, run]) => <div className="stat" key={source}><strong>{source}</strong><span>{run.status} · {run.items_created} créés · {run.items_updated} mis à jour</span></div>)}</section></main>; }
export default function AdminPage() { return <AuthGuard><AdminContent /></AuthGuard>; }
