"use client";

import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { AuthGuard } from "@/components/layout/AuthGuard";
import { ProductCard } from "@/components/products/ProductCard";
import { apiFetch, jsonBody } from "@/lib/api";
import { useAuthStore } from "@/stores/auth";
import type { CatalogItem, InteractionPayload, RecommendationResponse } from "@/types/api";

function ProductsContent() { const token = useAuthStore((state) => state.token); const client = useQueryClient(); const catalog = useQuery({ queryKey: ["catalog", "product"], queryFn: () => apiFetch<CatalogItem[]>("/api/v1/catalog?item_type=product&limit=50", {}, token!), enabled: Boolean(token) }); const recs = useQuery({ queryKey: ["recommendations", "product"], queryFn: () => apiFetch<RecommendationResponse>("/api/v1/recommendations/product?top_k=12", {}, token!), enabled: Boolean(token) }); const interaction = useMutation({ mutationFn: (payload: InteractionPayload) => apiFetch("/api/v1/interactions", { ...jsonBody(payload) }, token!), onSuccess: () => client.invalidateQueries({ queryKey: ["recommendations", "product"] }) }); const favorite = useMutation({ mutationFn: (id: number) => apiFetch(`/api/v1/favorites/${id}`, { ...jsonBody({}) }, token!), onSuccess: () => client.invalidateQueries({ queryKey: ["favorites"] }) }); const send = (id: number, event_type: InteractionPayload["event_type"]) => interaction.mutate({ catalog_item_id: id, event_type, source_page: "/products" }); if (catalog.isLoading || recs.isLoading) return <main className="center-page"><p>Chargement des produits…</p></main>; const recommendations = recs.data?.recommendations ?? []; const products = catalog.data ?? []; return <main className="page"><div className="hero"><div><p className="eyebrow">Sélection eBay</p><h1>Produits utiles.</h1><p>Une sélection de produits issus des recherches eBay configurées pour RecoSphere.</p></div></div><section className="section"><h2>Recommandés pour vous</h2>{recommendations.length ? <div className="movie-grid">{recommendations.map((item) => <ProductCard key={item.catalog_item_id} item={item.detail} onLike={(id) => send(id, "like")} onDislike={(id) => send(id, "dislike")} onFavorite={(id) => favorite.mutate(id)} />)}</div> : <p className="empty">Aucune recommandation produit pour le moment.</p>}</section><section className="section"><h2>À découvrir</h2>{products.length ? <div className="movie-grid">{products.map((item) => <ProductCard key={item.id} item={item} onLike={(id) => send(id, "like")} onDislike={(id) => send(id, "dislike")} onFavorite={(id) => favorite.mutate(id)} />)}</div> : <p className="empty">Aucun produit synchronisé. Un administrateur doit lancer la synchronisation eBay.</p>}</section></main>; }
export default function ProductsPage() { return <AuthGuard><ProductsContent /></AuthGuard>; }
