"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { AuthGuard } from "@/components/layout/AuthGuard";
import { apiFetch, jsonBody } from "@/lib/api";
import { useAuthStore } from "@/stores/auth";
import type { CatalogItem, InteractionPayload } from "@/types/api";

function ProductDetailContent() { const params = useParams<{ id: string }>(); const token = useAuthStore((state) => state.token); const client = useQueryClient(); const query = useQuery({ queryKey: ["product", params.id], queryFn: () => apiFetch<CatalogItem>(`/api/v1/catalog/${params.id}`, {}, token!), enabled: Boolean(token && params.id) }); const interaction = useMutation({ mutationFn: (event_type: InteractionPayload["event_type"]) => apiFetch("/api/v1/interactions", { ...jsonBody({ catalog_item_id: Number(params.id), event_type, source_page: `/products/${params.id}` }) }, token!), onSuccess: () => client.invalidateQueries({ queryKey: ["recommendations", "product"] }) }); const favorite = useMutation({ mutationFn: () => apiFetch(`/api/v1/favorites/${params.id}`, { ...jsonBody({}) }, token!), onSuccess: () => client.invalidateQueries({ queryKey: ["favorites"] }) }); if (query.isLoading) return <main className="center-page"><p>Chargement du produit…</p></main>; if (!query.data) return <main className="center-page"><div className="form-card"><h1>Produit introuvable</h1><Link href="/products" className="button">Retour aux produits</Link></div></main>; const item = query.data; return <main className="detail"><Link href="/products" className="eyebrow">← Tous les produits</Link><div className="detail-layout" style={{ marginTop: 25 }}><div>{item.image_url ? <img className="detail-poster" src={item.image_url} alt={item.title} /> : <div className="detail-poster poster-placeholder">🛍️</div>}</div><div><p className="eyebrow">Produit</p><h1>{item.title}</h1><p className="meta">{item.brand ?? "Marque non précisée"} · {item.condition ?? "État non précisé"}</p>{item.price_amount != null && <p className="rating">{item.price_amount.toFixed(2)} {item.price_currency ?? "EUR"}</p>}<p className="description">{item.description || "Aucune description disponible."}</p><div className="detail-actions"><button className="button" onClick={() => interaction.mutate("like")}>♥ J’aime</button><button className="button secondary" onClick={() => interaction.mutate("dislike")}>Je n’aime pas</button><button className="button secondary" onClick={() => favorite.mutate()}>☆ Favori</button>{item.product_url && <a className="button secondary" href={item.product_url} target="_blank" rel="noreferrer" onClick={() => interaction.mutate("purchase_redirect")}>Voir sur eBay</a>}</div></div></div></main>; }
export default function ProductDetailPage() { return <AuthGuard><ProductDetailContent /></AuthGuard>; }
